#
# Test script for backend HTTP requests.
#

@base_url = http://localhost:5000

###
# Adds an item to the todo list.
#

POST {{base_url}}/todo
Content-Type: application/json

{
    "todoItem": {
        "text": "Put the bins out."
    }
}

###
# Gets the todo list.
#

GET {{base_url}}/todos

